### ISSUE TITLE
media controls not working

### ISSUE THREAD

**Issue by MeowRay** [LAB02-Research/HASS.Agent-Integration#9] opened 2022-12-15 15:25 UTC

**Comment by LAB02-Admin** [comment] 2022-12-16 08:07
Too little information, but possible duplicate of [[#229](https://github.com/LAB02-Research/HASS.Agent/issues/229)]

**Closed by LAB02-Admin** 2022-12-16 08:07 UTC

**Comment by MeowRay** [comment] 2022-12-19 18:50
> Too little information, but possible duplicate of [[#229](https://github.com/LAB02-Research/HASS.Agent/issues/229)]

Media controls do not work when used as a media source for "Music Assistant",
There also seems to be no way to pause/stop when playing a media file directly
